export const FETCH_SIGNUP_SUCCESS = 'FETCH_SIGNUP_SUCCESS'
export const FETCH_SIGNUP_FAILS = 'FETCH_SIGNUP_FAILS'
export const FETCH_SIGNUP_BEGIN = 'FETCH_SIGNUP_BEGIN'

export const FETCH_LOGIN_SUCCESS = 'FETCH_SIGNIN_SUCCESS'
export const FETCH_LOGIN_FAILS = 'FETCH_SIGNIN_FAILS'
export const FETCH_LOGIN_BEGIN = 'FETCH_SIGNIN_BEGIN'

export const FETCH_SIGNOUT_SUCCESS = 'FETCH_SIGNOUT_SUCCESS'

export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS'
export const FETCH_ARTICLES_FAILS = 'FETCH_ARTICLES_FAILS'
export const FETCH_ARTICLES_BEGIN = 'FETCH_ARTICLES_BEGIN'

export const PAGE_LINK = 'PAGE_LINK'
export const FEED_TYPE = "FEED_TYPE"

export const POST_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS'
export const POST_ARTICLES_FAILS = 'FETCH_ARTICLES_FAILS'
export const POST_ARTICLES_BEGIN = 'FETCH_ARTICLES_BEGIN'

export const GET_ART_USER_SUCCESS = 'GET_ART_USER_SUCCESS'
export const GET_ART_USER_FAILS = 'GET_ART_USER_FAILS'
export const GET_ART_USER_BEGIN = 'GET_ART_USER_BEGIN'

